In [76]:
import pandas as pd
import numpy as np
import csv

In [77]:
row = pd.read_csv("C:\\Users\\msi-\\Documents\\rowData.txt", header = None)
row

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
792    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
793    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
794    1    1    1    1    1    1    1    1    1    1  ...    1    0    0   
795    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
796    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     393  394  395  396  397  398  399  
0      0    0    0    0    0    0    0  
1      0    0    0    0    0    0    0  
2      0    0    0    0    0    0    0  
3      0    0    0    0    0    0    0  
4      0    0    0    0    0    0    0  
..   ...  ...  ...  ...  ...  ...  ...  
792    0    0    0    0    0    0    0  
793    0    0    0    0    0    0    0  
794    1    0    1    0    0    1    0  
795    0    0    0    0    0    0    0  
796    0    0    0    0    0    0    0  

[797 rows x 400 columns]

In [78]:
col = pd.read_csv("C:\\Users\\msi-\\Documents\\colData.txt", header = None)
col

0     1     2     3     4     5     6     7     8     9     ...  1732  \
0       1     0     0     0     1     1     0     0     1     0  ...     0   
1       1     0     0     0     1     1     0     0     1     0  ...     0   
2       1     0     0     0     1     1     0     0     1     0  ...     0   
3       1     0     0     0     1     1     0     0     1     0  ...     0   
4       1     0     0     0     1     1     0     0     1     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
395     1     1     0     1     1     0     1     0     1     1  ...     0   
396     1     1     0     1     1     1     1     0     1     0  ...     0   
397     1     0     0     1     1     1     0     0     1     0  ...     0   
398     1     1     0     1     1     1     1     0     1     0  ...     0   
399     1     1     0     1     1     1     1     0     1     0  ...     0   

     1733  1734  1735  1736  1737  1738  1739  1740  1741  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
395     0     0     0     0     0     0     0     0     0  
396     0     0     0     0     0     0     0     0     0  
397     0     0     0     0     0     0     0     0     0  
398     0     0     0     0     0     0     0     0     0  
399     0     0     0     0     0     0     0     0     0  

[400 rows x 1742 columns]

In [79]:
row.iloc[:, 1]

0      0
1      0
2      0
3      0
4      0
      ..
792    0
793    0
794    1
795    0
796    0
Name: 1, Length: 797, dtype: int64

In [80]:
n = 400
user = row.shape[0]
item = col.shape[1]
user, item

(797, 1742)

In [81]:
row = np.array(row).astype(bool)
col = np.array(col).astype(bool)
row.shape, col.shape

((797, 400), (400, 1742))

In [82]:
rowZip = []
tmp = np.arange(user)
for i in range(n):
    rowZip.append(tmp[row[:, i]])
rowZip

[array([ 12,  42, 170, 186, 216, 439, 461, 476, 493, 540, 547, 566, 605,
        755, 794]),
 array([ 12,  42, 170, 186, 439, 461, 476, 540, 547, 566, 580, 605, 625,
        755, 794]),
 array([ 12,  42, 170, 186, 439, 461, 476, 493, 540, 547, 580, 605, 625,
        755, 794]),
 array([ 12,  42, 170, 439, 461, 476, 493, 540, 547, 566, 580, 605, 625,
        755, 794]),
 array([ 12,  42, 170, 186, 439, 461, 476, 493, 540, 547, 566, 580, 605,
        755, 794]),
 array([ 12,  42, 170, 186, 439, 476, 493, 540, 547, 566, 580, 605, 625,
        755, 794]),
 array([ 12,  42, 170, 186, 439, 461, 476, 493, 540, 547, 566, 605, 625,
        755, 794]),
 array([ 12,  42, 170, 186, 320, 439, 461, 476, 493, 540, 547, 566, 605,
        755, 794]),
 array([ 12,  42, 186, 320, 461, 476, 493, 540, 547, 566, 580, 605, 625,
        755, 794]),
 array([ 12,  42, 186, 439, 461, 476, 493, 540, 547, 566, 580, 605, 625,
        755, 794]),
 array([ 42,  71, 119, 170, 320, 369, 445, 461, 493, 518, 540, 547, 55

In [83]:
colZip = []
tmp = np.arange(item)
for i in range(n):
    colZip.append(tmp[col[i, :]])
colZip

[array([  0,   4,   5,   8,  10,  13,  18,  19,  23,  26,  32,  35,  36,
         37,  51,  58,  60,  66,  82,  99, 110, 136, 253]),
 array([  0,   4,   5,   8,  10,  18,  19,  23,  27,  32,  35,  36,  37,
         51,  58,  60,  62,  66,  99, 110, 136, 228, 253]),
 array([  0,   4,   5,   8,  10,  18,  19,  23,  27,  32,  35,  36,  37,
         39,  51,  58,  60,  62,  66,  99, 110, 136, 253]),
 array([  0,   4,   5,   8,  10,  18,  19,  23,  27,  32,  35,  36,  37,
         51,  58,  60,  62,  66,  88,  99, 110, 136, 253]),
 array([  0,   4,   5,   8,  10,  18,  19,  23,  27,  32,  35,  36,  37,
         51,  58,  60,  62,  66,  82,  99, 110, 136, 253]),
 array([  0,   4,   5,   8,   9,  10,  18,  19,  23,  27,  32,  35,  36,
         37,  51,  58,  60,  62,  66,  99, 110, 136, 253]),
 array([  0,   4,   5,   8,  10,  18,  19,  23,  26,  27,  32,  35,  36,
         37,  51,  58,  60,  62,  66,  99, 110, 136, 253]),
 array([  0,   4,   5,   8,  10,  13,  18,  19,  23,  26,  27,  32,  

In [84]:
max([max(i) for i in colZip])

253

In [85]:
','.join(colZip[1].astype(str))

'0,4,5,8,10,18,19,23,27,32,35,36,37,51,58,60,62,66,99,110,136,228,253'

In [86]:
with open('rowZip.csv', 'w', newline='') as file:
    for i in range(n):
        file.write(','.join(rowZip[i].astype(str)) + '\n')

In [87]:
with open('colZip.csv', 'w', newline='') as file:
    for i in range(n):
        file.write(','.join(colZip[i].astype(str)) + '\n')

In [88]:
[len(i) for i in rowZip]

[15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,


In [89]:
[len(i) for i in colZip]

[23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 23,
 23,
 23,
 23,
 23,
 24,
 23,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
