In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
row = pd.read_csv("C:\\Users\\msi-\\Documents\\rowData.txt", header = None)
row

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
792    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
793    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
794    0    0    0    1    1    1    1    1    1    1  ...    0    0    0   
795    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
796    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     393  394  395  396  397  398  399  
0      0    0    0    0    0    0    0  
1      0    0    0    0    0    0    0  
2      0    0    0    0    0    0    0  
3      0    0    0    0    0    0    0  
4      0    0    0    0    0    0    0  
..   ...  ...  ...  ...  ...  ...  ...  
792    0    0    0    0    0    0    0  
793    0    0    0    0    0    0    0  
794    0    0    0    0    0    0    0  
795    0    0    0    0    0    0    0  
796    0    0    0    0    0    0    0  

[797 rows x 400 columns]

In [3]:
col = pd.read_csv("C:\\Users\\msi-\\Documents\\colData.txt", header = None)
col

0     1     2     3     4     5     6     7     8     9     ...  1732  \
0       1     1     1     1     0     1     1     1     0     0  ...     0   
1       1     1     1     1     0     0     1     1     0     0  ...     0   
2       1     1     1     1     0     1     1     1     0     0  ...     0   
3       1     1     1     1     1     1     1     0     1     0  ...     0   
4       1     1     1     1     1     1     1     0     1     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
395     1     1     1     1     0     1     1     1     1     0  ...     0   
396     1     1     1     1     1     1     1     1     0     0  ...     0   
397     1     1     1     1     0     1     1     1     1     0  ...     0   
398     1     1     1     1     0     1     1     1     0     0  ...     0   
399     1     1     1     1     1     1     1     1     0     0  ...     0   

     1733  1734  1735  1736  1737  1738  1739  1740  1741  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
395     0     0     0     0     0     0     0     0     0  
396     0     0     0     0     0     0     0     0     0  
397     0     0     0     0     0     0     0     0     0  
398     0     0     0     0     0     0     0     0     0  
399     0     0     0     0     0     0     0     0     0  

[400 rows x 1742 columns]

In [4]:
row.iloc[:, 1]

0      0
1      0
2      0
3      0
4      0
      ..
792    0
793    0
794    0
795    0
796    0
Name: 1, Length: 797, dtype: int64

In [5]:
n = 400
user = row.shape[0]
item = col.shape[1]
user, item

(797, 1742)

In [6]:
row = np.array(row).astype(bool)
col = np.array(col).astype(bool)
row.shape, col.shape

((797, 400), (400, 1742))

In [7]:
rowZip = []
tmp = np.arange(user)
for i in range(n):
    rowZip.append(tmp[row[:, i]])
rowZip

[array([ 11,  42,  71, 108, 119, 174, 215, 246, 284, 461, 540, 547, 641,
        755, 756]),
 array([ 11,  71, 108, 119, 174, 215, 246, 284, 425, 461, 540, 547, 641,
        755, 756]),
 array([ 11,  71, 108, 119, 170, 174, 215, 246, 284, 461, 540, 547, 641,
        755, 756]),
 array([ 42,  69,  71,  79, 119, 170, 174, 186, 216, 461, 493, 540, 547,
        571, 794]),
 array([ 12,  42,  69,  71, 119, 170, 174, 186, 320, 445, 461, 518, 547,
        571, 794]),
 array([ 17,  42,  69,  71, 119, 170, 174, 186, 320, 445, 461, 518, 547,
        571, 794]),
 array([ 42,  69,  71, 119, 170, 174, 186, 320, 445, 461, 518, 547, 571,
        755, 794]),
 array([ 42,  69,  71,  79, 119, 170, 174, 186, 320, 445, 461, 518, 547,
        571, 794]),
 array([ 12,  42,  69,  71,  79, 119, 170, 174, 186, 216, 445, 461, 547,
        571, 794]),
 array([ 42,  69,  71,  79, 119, 170, 174, 186, 216, 445, 461, 493, 547,
        571, 794]),
 array([ 42,  69,  71,  79, 119, 170, 174, 186, 216, 320, 445, 461, 54

In [8]:
colZip = []
tmp = np.arange(item)
for i in range(n):
    colZip.append(tmp[col[i, :]])
colZip

[array([  0,   1,   2,   3,   5,   6,   7,  11,  12,  16,  20,  26,  27,
         37,  47,  48,  50, 113, 125, 128]),
 array([  0,   1,   2,   3,   6,   7,  11,  12,  16,  20,  26,  27,  37,
         47,  48,  50,  77, 113, 125, 128]),
 array([  0,   1,   2,   3,   5,   6,   7,  11,  12,  16,  20,  26,  27,
         37,  47,  48,  77, 113, 125, 128]),
 array([  0,   1,   2,   3,   4,   5,   6,   8,  11,  14,  20,  26,  37,
         39,  47,  49,  51,  78,  99, 136]),
 array([  0,   1,   2,   3,   4,   5,   6,   8,  11,  14,  27,  37,  39,
         48,  49,  51,  78, 104, 136, 147]),
 array([  0,   1,   3,   4,   5,   6,   8,  11,  14,  27,  37,  39,  47,
         48,  49,  51,  78, 104, 136, 147]),
 array([  0,   1,   2,   3,   4,   5,   6,   8,  11,  14,  27,  37,  39,
         47,  48,  51,  78, 104, 136, 147]),
 array([  0,   1,   2,   3,   4,   5,   6,   8,  11,  14,  37,  39,  47,
         48,  49,  51,  78, 104, 136, 147]),
 array([  0,   1,   2,   3,   4,   5,   6,   8,  11,  14

In [9]:
max([max(i) for i in colZip])

245

In [10]:
','.join(colZip[1].astype(str))

'0,1,2,3,6,7,11,12,16,20,26,27,37,47,48,50,77,113,125,128'

In [11]:
with open('rowZip.csv', 'w', newline='') as file:
    for i in range(n):
        file.write(','.join(rowZip[i].astype(str)) + '\n')

In [12]:
with open('colZip.csv', 'w', newline='') as file:
    for i in range(n):
        file.write(','.join(colZip[i].astype(str)) + '\n')

In [13]:
import random
random.sample(set([1,2,3]),2)

[3, 1]