In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
row = pd.read_csv("C:\\Users\\msi-\\Documents\\rowData.txt", header = None)
row

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2      0    1    1    1    1    0    0    1    1    1  ...    0    0    0   
3      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
792    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
793    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
794    1    0    1    1    0    0    0    1    1    1  ...    1    1    1   
795    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
796    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     393  394  395  396  397  398  399  
0      0    0    0    0    0    0    0  
1      0    0    0    0    0    0    0  
2      0    0    0    0    0    0    0  
3      0    0    0    0    0    0    0  
4      0    0    0    0    0    0    0  
..   ...  ...  ...  ...  ...  ...  ...  
792    0    0    0    0    0    0    0  
793    0    0    0    0    0    0    0  
794    1    1    1    1    1    1    1  
795    0    0    0    0    0    0    0  
796    0    0    0    0    0    0    0  

[797 rows x 400 columns]

In [3]:
col = pd.read_csv("C:\\Users\\msi-\\Documents\\colData.txt", header = None)
col

0     1     2     3     4     5     6     7     8     9     ...  1732  \
0       0     0     0     0     1     1     1     0     1     1  ...     0   
1       0     1     1     1     1     0     1     0     0     0  ...     0   
2       0     1     1     1     1     0     1     0     0     0  ...     0   
3       0     1     1     1     1     0     1     0     0     0  ...     0   
4       0     1     1     1     1     0     1     1     0     0  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
395     1     1     1     0     1     0     1     0     1     0  ...     0   
396     1     1     1     0     1     0     1     0     1     0  ...     0   
397     0     0     0     0     1     1     1     0     0     0  ...     0   
398     0     0     0     0     1     1     1     0     0     0  ...     0   
399     0     0     0     0     1     1     1     0     0     0  ...     0   

     1733  1734  1735  1736  1737  1738  1739  1740  1741  
0       0     0     0     0     0     0     0     0     0  
1       0     0     0     0     0     0     0     0     0  
2       0     0     0     0     0     0     0     0     0  
3       0     0     0     0     0     0     0     0     0  
4       0     0     0     0     0     0     0     0     0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
395     0     0     0     0     0     0     0     0     0  
396     0     0     0     0     0     0     0     0     0  
397     0     0     0     0     0     0     0     0     0  
398     0     0     0     0     0     0     0     0     0  
399     0     0     0     0     0     0     0     0     0  

[400 rows x 1742 columns]

In [4]:
row.iloc[:, 1]

0      0
1      0
2      1
3      0
4      0
      ..
792    0
793    0
794    0
795    0
796    0
Name: 1, Length: 797, dtype: int64

In [5]:
n = 400
user = row.shape[0]
item = col.shape[1]
user, item

(797, 1742)

In [6]:
row = np.array(row).astype(bool)
col = np.array(col).astype(bool)
row.shape, col.shape

((797, 400), (400, 1742))

In [7]:
rowZip = []
tmp = np.arange(user)
for i in range(n):
    rowZip.append(tmp[row[:, i]])
rowZip

[array([ 12,  17,  40,  42,  69, 176, 216, 320, 358, 439, 445, 493, 518,
        540, 547, 571, 580, 590, 596, 641, 694, 706, 755, 794]),
 array([  2,  12,  37,  42,  58, 108, 170, 207, 215, 216, 320, 425, 439,
        459, 461, 493, 540, 547, 606, 641, 734, 739, 755, 756]),
 array([  2,  12,  37,  42,  58, 108, 170, 207, 216, 320, 425, 430, 439,
        459, 461, 493, 540, 547, 606, 641, 739, 755, 756, 794]),
 array([  2,  37,  39,  58, 108, 147, 170, 207, 216, 320, 425, 430, 439,
        461, 493, 540, 547, 606, 641, 739, 755, 756, 769, 794]),
 array([  2,  37,  39,  42,  58, 108, 170, 215, 216, 320, 425, 439, 459,
        461, 493, 540, 547, 606, 641, 734, 739, 755, 756, 769]),
 array([ 12,  37,  42,  58,  68, 108, 170, 186, 215, 320, 408, 425, 439,
        461, 490, 493, 540, 547, 641, 734, 739, 755, 756, 769]),
 array([ 12,  37,  42,  58, 108, 170, 186, 215, 320, 398, 425, 430, 439,
        461, 490, 493, 540, 547, 641, 734, 739, 755, 756, 769]),
 array([  2,  42,  58, 108, 170, 2

In [8]:
colZip = []
tmp = np.arange(item)
for i in range(n):
    colZip.append(tmp[col[i, :]])
colZip

[array([  4,   5,   6,   8,   9,  11,  14,  18,  39,  51,  58,  70,  85,
        136]),
 array([ 1,  2,  3,  4,  6, 11, 13, 18, 19, 32, 33, 37, 41, 71]),
 array([ 1,  2,  3,  4,  6, 11, 13, 18, 19, 32, 33, 37, 71, 82]),
 array([  1,   2,   3,   4,   6,  11,  12,  13,  18,  19,  32,  33,  71,
        111]),
 array([ 1,  2,  3,  4,  6,  7, 11, 13, 18, 19, 32, 33, 41, 71]),
 array([ 1,  3,  4,  6, 11, 13, 16, 18, 19, 26, 27, 32, 33, 41]),
 array([ 1,  2,  3,  4,  6, 11, 13, 16, 18, 19, 26, 27, 32, 33]),
 array([ 0,  1,  2,  3,  4, 12, 13, 18, 19, 32, 33, 37, 71, 82]),
 array([ 0,  1,  2,  3,  4,  6, 11, 18, 19, 32, 33, 37, 71, 85]),
 array([ 0,  1,  2,  3,  4,  6, 11, 13, 18, 19, 32, 33, 37, 71]),
 array([ 0,  1,  2,  3,  4,  6, 11, 18, 19, 32, 33, 37, 70, 71]),
 array([ 0,  1,  2,  3,  4,  6, 11, 19, 32, 33, 37, 70, 71, 85]),
 array([ 0,  1,  2,  3,  4,  6, 11, 18, 19, 32, 33, 70, 71, 85]),
 array([ 1,  2,  3,  4,  6, 11, 18, 19, 32, 33, 37, 70, 71, 85]),
 array([ 0,  1,  2,  3,  4,  6, 

In [9]:
max([max(i) for i in colZip])

159

In [10]:
','.join(colZip[1].astype(str))

'1,2,3,4,6,11,13,18,19,32,33,37,41,71'

In [11]:
with open('rowZip.csv', 'w', newline='') as file:
    for i in range(n):
        file.write(','.join(rowZip[i].astype(str)) + '\n')

In [12]:
with open('colZip.csv', 'w', newline='') as file:
    for i in range(n):
        file.write(','.join(colZip[i].astype(str)) + '\n')

In [13]:
[len(i) for i in rowZip]

[24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 25,
 24,
 24,
 24,
 24,
 25,
 25,
 25,
 24,
 26,
 24,
 24,
 24,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 27,
 24,
 25,
 26,
 25,
 25,
 25,
 24,
 25,
 25,
 24,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 25,
 24,
 24,
 25,
 24,
 24,
 24,
 24,
 28,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 26,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 26,
 25,
 24,
 26,
 24,
 24,
 24,
 25,
 27,
 24,
 26,
 25,
 25,
 25,
 24,
 24,
 24,
 24,
 27,
 25,
 25,
 24,
 24,
 24,
 26,
 24,
 24,
 26,
 26,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 24,
 25,
 24,
 24,
 25,
 24,
 24,
 26,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,


In [14]:
[len(i) for i in colZip]

[14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
